### ISSUE TITLE
use without ConversationID

### ISSUE THREAD

**Issue by viprocket1** [e2b-dev/chatgpt-plugin#7]
I want to use this on a GPT4 wrapper, which used GPT4 API. how can i use this without [Conversation_id](https://community.openai.com/t/conversation-id/33270). 

I was able to execute the chain but got error with 

```
Listening at http://localhost:3000
GET / 500 23 - 2.567 ms
Caught Internal Error for /files: Error: conversationID in header is required
    at getUserSessionID (/home/runner/chatgpt-plugin-1/src/plugin/environment.ts:17:11)
    at FileController.readFile (/home/runner/chatgpt-plugin-1/src/plugin/fileController.ts:37:23)
    at FileController_readFile (/home/runner/chatgpt-plugin-1/src/generated/routes.ts:87:51)
    at Layer.handle (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/layer.js:95:5)
    at <anonymous> (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/index.js:284:15)
    at Function.process_params (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/index.js:280:10)
GET /files?env=Nodejs&path=file.txt 500 35 - 43.081 ms
    Caught Internal Error for /files: Error: conversationID in header is required
    at getUserSessionID (/home/runner/chatgpt-plugin-1/src/plugin/environment.ts:17:11)
    at FileController.readFile (/home/runner/chatgpt-plugin-1/src/plugin/fileController.ts:37:23)
    at FileController_readFile (/home/runner/chatgpt-plugin-1/src/generated/routes.ts:87:51)
    at Layer.handle (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/layer.js:95:5)
    at <anonymous> (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/index.js:284:15)
    at Function.process_params (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/chatgpt-plugin-1/node_modules/express/lib/router/index.js:280:10)
GET /files?env=Nodejs&path=file.txt 500 35 - 39.320 ms```

**Comment by ValentaTomas** [comment]
Hi, if you have control of the GPT4 wrapper you can just generate a random string and send it as the conversation id header. What you should also do it keep track of the generated ID and send it with the next request too - the header identifies the cloud environment you are using so if you use a different ID it will connect/create a new environment!

**Comment by ValentaTomas** [comment]
@viprocket1 I would actually recommend that you check our SDK (https://github.com/e2b-dev/e2b) because I think you really just want to use the environment from your code, right?

**Comment by viprocket1** [comment]
im checking the sdk out. i went for the plugin because it has the OpenAPI.json. i can import tools in my hosted environment if the tool has a OpenAPI.json. any way i can generate OpenAPI specs for SDK?

**Comment by viprocket1** [comment]
> Hi, if you have control of the GPT4 wrapper you can just generate a random string and send it as the conversation id header. What you should also do it keep track of the generated ID and send it with the next request too - the header identifies the cloud environment you are using so if you use a different ID it will connect/create a new environment!

i did something like this but got the same error

![image](https://github.com/e2b-dev/chatgpt-plugin/assets/47239352/ef6ea035-8a3a-4711-a93a-774fc3c37824)

**Comment by viprocket1** [comment]
@ValentaTomas

**Comment by ValentaTomas** [comment]
The format of the header is actually not `conversationID`, but `openai-conversation-id` 
(https://github.com/e2b-dev/chatgpt-plugin/blob/main/src/constants.ts#L3) as per OpenAI docs.

**Comment by ValentaTomas** [comment]
> im checking the sdk out. i went for the plugin because it has the OpenAPI.json. i can import tools in my hosted environment if the tool has a OpenAPI.json. any way i can generate OpenAPI specs for SDK?

This is an interesting use case, can you give us a link to the GPT4 wrapper you are using?

**Comment by viprocket1** [comment]
@ValentaTomas https://www.aisandbox.co.in/tools

**Comment by viprocket1** [comment]
bruh it 

> The name of the header is actually not `conversationID`, but `openai-conversation-id` (https://github.com/e2b-dev/chatgpt-plugin/blob/main/src/constants.ts#L3) as per OpenAI docs.

bruh it worked tq tq
